# Generated by Django 4.2.4 on 2023-10-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_creditcard_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_status',
            field=models.CharField(choices=[['active', 'ACTIVE'], ['in_active', 'IN_ACTIVE']], default='in_active', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[['master_card', 'MASTER_CARD'], ['visa', 'VISA'], ['rupay', 'RUPAY'], ['platinum', 'PLATINUM']], max_length=20),
        ),
    ]
