# Generated by Django 4.2.4 on 2023-10-16 06:00

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_creditcard_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=22, max_length=3, prefix='', unique=True),
        ),
    ]
