# Generated by Django 4.2.4 on 2023-10-18 03:28

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_creditcard_amount_alter_creditcard_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=3, max_length=6, prefix='', unique=True),
        ),
    ]
